### ISSUE TITLE
Add favicon support

### ISSUE THREAD

**Issue by GarkGarcia** [GarkGarcia/icon_baker#4]
Follow up on https://github.com/GarkGarcia/icon-pie/issues/8.

**Comment by GarkGarcia** [comment]
@ngirard So, continuing from where we stopped in https://github.com/GarkGarcia/icon-pie/issues/8, we need to create some sort of interface for icons whose entries are named.

"Unamed icons" and "named icons" need to behave differently. What making the "entry-type" (named or unamed) a type parameter? So the `Icon` trait would now look something like:

```rust
pub trait Icon<E> {
    fn new() -> Self;

    fn add_entry<F: FnMut(&SourceImage, Size) -> Result<DynamicImage>>(
        &mut self,
        filter: F,
        source: &SourceImage,
        entry: &E
    ) -> Result<()>;

    fn add_entries<F: FnMut(&SourceImage, Size) -> Result<DynamicImage>,I: IntoIterator<Item = Entry>>(
        &mut self,
        mut filter: F,
        source: &SourceImage,
        entries: &I
    ) -> Result<()> {
        for entry in entries {
            self.add_entry(|src, size| filter(src, size), source, &entry)?;
        }

        Ok(())
    }

    fn write<W: Write>(&mut self, w: &mut W) -> io::Result<()>;

    fn save<P: AsRef<Path>>(&mut self, path: &mut P) -> io::Result<()> {
        let mut file = File::create(path.as_ref())?;
        self.write(&mut file)
    }
```

What do you think?

**Comment by ngirard** [comment]
I have no clue for now, but I can take a look tomorrow if you want.

**Comment by GarkGarcia** [comment]
That would be great!

**Comment by ngirard** [comment]
Alright well, speak to you tomorrow then !

**Comment by GarkGarcia** [comment]
By the way. Don't feel obligated to keep up with the development of the lib.

I'm tagging you in this discussion cuz I personally feel uncomfortable to run major changes to the API without letting you know, but I don't mind if you can't get involved at the moment.

**Comment by ngirard** [comment]
Hey @GarkGarcia, sorry for not keeping up with IconPie ! I didn't forget the project, but I'm currently involved in a major french festival, with logistics, security and whatnot. My duties will end on next monday, so you can expect to hear from me just after that !

One thing of interest: I noticed that the `mini_fs` crate we talked about doesn't have write support yet, so I've [asked it's author](https://github.com/germangb/mini-fs/issues/10) to consider adding it. Hopefully he will!

Cheers, and be back soon !

**Comment by GarkGarcia** [comment]
No worries. In the meantime, I'll release a beta version of `icon_baker` so that you can check out the API from `docs.rs`.

**Comment by GarkGarcia** [comment]
@ngirard Support for _favicons_ is out for [`icon_bakerv3.2.0-beta.2`](https://crates.io/crates/icon_baker)! Check it out. I also compiled my research into [this wiki page](https://github.com/GarkGarcia/icon-pie/wiki/Favicons).

There four thing we need to decide:

* Are we satisfied with the new general API of `icon_baker`? Take a look at the [docs](https://docs.rs/icon_baker/3.2.0-beta.2/icon_baker/).
* Are we going to support [Apple Touch Icons](https://docs.rs/icon_baker/3.2.0-beta.2/icon_baker/)?
* Are we going to support [Chrome Web App Icons](https://docs.rs/icon_baker/3.2.0-beta.2/icon_baker/)?
* Are we going to support [`.svg` files in the _favicon_ output](https://docs.rs/icon_baker/3.2.0-beta.2/icon_baker/)?

**Comment by GarkGarcia** [comment]
@ngirard In my opinion, we should support _Apple touch icons_. However, we shouldn't allow the user to customize it, which means the icons would look the same across all platforms.

I believe a similar approuch would be ideal for _Chrome web-app icons_.

Support for `.svg` file in the _favicon_ output is on it's way.

**Comment by GarkGarcia** [comment]
@ngirard What do you think?

**Comment by GarkGarcia** [comment]
Favicon support is now in the process of being stabilized.

**Comment by GarkGarcia** [comment]
Favicon support was stabilized on https://github.com/GarkGarcia/icon_baker/commit/c80653f1e0a5199e0715ce241ca27bf42cfb9365.
