### ISSUE TITLE
resvg: choosing the backend

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon_baker#5]
I've [asked upstream](https://github.com/RazrFalcon/resvg/issues/172) about how to decide between `resvg`'s supported backends, and we've got your answer:

> All backends will produce the same results. In case of a Rust project you should prefer `raqote` backend, but it's the slowest one at the moment (technically depends on what you need).

> The separation exist for an ability to use a native canvas when needed. For example, you can draw on a QWidget directly, without creating a raster image. As long as you don't need this, you can use whatever backend you want.

> Sadly, all backends require `harfbuzz`, so you still have to have a C++ compiler and CMake to actually build it. Unless you don't need text rendering at all (which is not optional right now).

**Comment by GarkGarcia** [comment]
In my opinion, `raqote` seems alright. What do you think?

**Comment by GarkGarcia** [comment]
Everything is ready for releasing the `raqote` backend version.

**Comment by GarkGarcia** [comment]
@ngirard Do you have any objections to the `raqote` backend? I'd like to sort this out as quickly as possible.

**Comment by ngirard** [comment]
Hey @GarkGarcia, sorry for not keeping up.

Sure, go for it.

I didn't have any objections about the raqote backend by opening this issue, I just wanted to report back informations.

**Comment by GarkGarcia** [comment]
Great! `raqote` it is for now I guess.
